name: "Cache Swift Dependencies"
description: "Cache Swift PM dependencies with platform-specific paths"
inputs:
  platform:
    description: "Platform identifier (linux, macos)"
    required: true
  cache-suffix:
    description: "Additional cache key suffix"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Cache Swift PM dependencies
      uses: actions/cache@v4
      with:
        path: |
          .build
          .build/prebuilts
          .build/repositories
          .build/checkouts
        key: ${{ inputs.platform }}-${{ inputs.cache-suffix }}-${{ hashFiles('Package.resolved') }}
