name: "Setup Debug Session"
description: "Set up tmate debugging session if enabled"
inputs:
  debug_enabled:
    description: "Enable debug session"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled == 'true' }}
