name: Tests on Xcode 26

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-xcode26:
    name: Test on Xcode 26
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Use Xcode 26
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0.0"
      - name: Cache Swift PM dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-xcode26-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode26-
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Build and Test
        run: swift test
