name: Build on Xcode 15

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-xcode15:
    name: Build on Xcode 15
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: .build
          key: .build-xcode15
      - name: Use Xcode 15.4
        run: xcodes select 15.4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Build only
        run: swift build
