name: Swift Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  test-xcode16:
    name: Test on Xcode 16
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: .build
          key: .build
      - name: Use Xcode 16.3
        run: xcodes select 16.3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Build and Test
        run: swift test

  test-xcode15:
    name: Test on Xcode 15
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: .build
          key: .build
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Build and Test
        run: swift test

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Build and Test
        run: swift test
