name: Swift Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-xcode16:
    name: Test on Xcode 16
    runs-on: macos-15-arm64
    steps:
      - uses: actions/checkout@v3
      - name: Use Xcode 16.3
        run: xcodes select 16.3
      - name: Build and Test
        run: swift test

  test-xcode15:
    name: Test on Xcode 15
    runs-on: macos-15-arm64
    steps:
      - uses: actions/checkout@v3
      - name: Build and Test
        run: swift test

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git for HTTPS instead of SSH
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - name: Build and Test
        run: swift test
